name: opvious-api-std
services:
  server:
    image: opvious/api-server:$IMAGE_TAG
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - ADMIN_EMAILS
      - BUCKET_URL=file:///mnt/bucket
      - DB_URL
      - LOG_LEVEL
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
      - OTEL_TRACES_SAMPLER=traceidratio
      - OTEL_TRACES_SAMPLER_ARG
      - REDIS_URL
    ports:
      - $PORT:8080
    volumes:
      - $BUCKET_PATH:/mnt/bucket:rw
  db:
    image: postgres:15-alpine
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      POSTGRES_DB: opvious
      POSTGRES_PASSWORD: $PASSWORD
  redis:
    image: redis:7-alpine
    command: redis-server --requirepass $PASSWORD
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 3s
      retries: 15
