name: opvious-api
services:
  server:
    image: opvious/api-server:$IMAGE_TAG
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      BUCKET_URL: file:///mnt/bucket
      DB_URL: postgres://postgres:$SECRET@db/opvious
      LL: $LOG_LEVEL
      OPVIOUS_API_IMAGE_EULA: $OPVIOUS_API_IMAGE_EULA
      REDIS_URL: redis://:$SECRET@redis
      STATIC_TOKENS: $STATIC_TOKENS
    ports:
      - $PORT:8080
    volumes:
      - $BUCKET_PATH:/mnt/bucket:rw
  db:
    image: postgres:15-alpine
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      POSTGRES_DB: opvious
      POSTGRES_PASSWORD: $SECRET
  redis:
    image: redis:7-alpine
    command: redis-server --requirepass $SECRET
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 3s
      retries: 15
