name: opvious-api
services:
  server:
    image: opvious/api-server
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DB_URL: postgres://postgres:$POSTGRES_PASS@db/opvious
      REDIS_URL: redis://:$REDIS_PASS@redis
    ports:
      - '8080:8080'
  db:
    image: postgres:15-alpine
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      POSTGRES_DB: opvious
      POSTGRES_PASSWORD: $POSTGRES_PASS
  redis:
    image: redis:7-alpine
    command: redis-server --requirepass $REDIS_PASS
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 3s
      retries: 15
