name: opvious-api
services:
  server:
    image: opvious/api-server:$IMAGE_TAG
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      BUCKET_URL: file:///mnt/bucket
      DB_URL: postgres://postgres:$POSTGRES_PASS@db/opvious
      LL: $LOG_LEVEL
      REDIS_URL: redis://:$REDIS_PASS@redis
      STATIC_TOKENS: $STATIC_TOKENS
    ports:
      - '8080:8080'
    volumes:
      - $BUCKET_PATH:/mnt/bucket
  db:
    image: postgres:15-alpine
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      POSTGRES_DB: opvious
      POSTGRES_PASSWORD: $POSTGRES_PASS
  redis:
    image: redis:7-alpine
    command: redis-server --requirepass $REDIS_PASS
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 3s
      retries: 15
