schema:
  - ./node_modules/@opvious/api-operations/resources/schema.gql
documents: ./node_modules/@opvious/api-operations/resources/operations/**/*.graphql
generates:
  ./src/graph.gen.ts:
    plugins:
      - typescript
      - typescript-generic-sdk
      - typescript-operations
    config:
      dedupeFragments: true
      documentMode: string
      enumsAsTypes: true
      immutableTypes: true
      maybeValue: T | undefined
      rawRequest: true
      strictScalars: true
      scalars:
        AccessToken: string
        AttemptLimit: number
        AttemptNotificationLimit: number
        AuthorizationName: string
        Cursor: string
        DateTime: string
        Description: string
        DisplayName: string
        Duration: number
        ExtendedFloat: number | string
        Failure: any
        FormulationName: string
        KeyItem: number | string
        Label: string
        Limit: number
        Long: string
        Slug: string
        Source: string
        TagName: string
        TensorBound: number | string
        Url: string
        Uuid: string
      useTypeImports: true
