name: Release
on:
  release:
    types:
      - published
jobs:
  tag:
    name: Tag NPM packages
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          registry-url: https://registry.npmjs.org
      - name: Extract version
        id: extract-version
        run: |
          echo "PACKAGE_VERSION=${GITHUB_REF#refs/tags/v}" >>"$GITHUB_OUTPUT"
      - name: Tag packages
        run: |
          for p in opvious{,-cli,-sheets}; do
            for t in beta latest; do
              npm dist-tag add "$p@$PACKAGE_VERSION" "$t"
            done
          done
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          PACKAGE_VERSION: ${{ steps.extract-version.outputs.PACKAGE_VERSION }}
